import sys, os
os.system('clear')
os.system('chmod +x install.py; chmod +x instructions.py; chmod +x main.py')
print('Установка необходимых дерикторий/зависемостей')
os.system('pip install --uprade pip')
os.system('pip3 install pyfiglet')
os.system('pip3 install colorama')
os.system('pip3 install config')
os.system('pip3 install threading')
os.system('pip3 install bs4')
os.system('pip3 install requests')
os.system('pip3 install user_agent')
os.system('clear')
print('[~]Установка завершена!')
print('=======================')
print('Пропишите команду: python instructions.py')